version: '3.1'
services:
  application:
    build:
      context: ./
      dockerfile: ./docker/application/Dockerfile
    volumes: 
      - .:/var/www:rw
    command: >
      bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - database
    ports:
      - 3000:3000

  database:
    image: postgres:11.5
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  asset:
    build: 
      context: ./
      dockerfile: ./docker/asset/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./public:/var/www/public
      - ./client:/var/www/client
    command: >
      yarn run start

volumes:
  database_volume:
    driver: local